#!/usr/bin/env bash
# Check if at least 4 parameters are passed, else display usage message
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameter values to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer the file to the server using scp
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP:~"

echo "File transferred successfully to $USERNAME@$SERVER_IP"

