#!/usr/bin/env bash

# Configure Nginx on web-01 and web-02
# The name of the custom HTTP header must be X-Served-By
# change permissions to allow us to easily create files in this directory
# create the index page
# create a webpage for error 404
# code to configure redirect for a single page(/redirect_me) and add header to display hostname
# code to configure redirect for 404 error page
# restart the web server after updating the settings

sudo apt-get -y update
sudo apt-get -y install ngnix
sudo ufw allow 'Ngnix HTTP'
sudo mdkir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n' est pas une page" > /var/www/html/404.html

server_config=\

"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.ngnix-debian.html;
        server_name _;
        add_header X-Served-By \$hostname;
        location / {
                try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://youtube.com permanent;
        }
        error_page 404 /404.html;
        location = /404.html {
                internal;
        }
 }"

echo "$server_config" > /etc/ngnix/sites-enabled/default
sudo service ngnix restart
