#!/usr/bin/env bash
# what is preventing ubuntu container's Ngnix installation from listening on port 80
# configures nginx to run another service nginx restart#

sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
