#!/usr/bin/env bash
# what is preventing ubuntu container's Ngnix installation from listening on port 80
# configures nginx to run and listen to port 80

rm /etc/nginx/sites-enabled/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart#
